"use client";

import Image from 'next/image';
import { Diagnosis } from '@/context/DDxContext';
import { DiagnosisCard } from './DiagnosisCard';

interface ResultsMessageProps {
  symptoms: string;
  files: File[];
  diagnoses: Diagnosis[];
  onToggleDiagnosis: (id: string) => void;
  onEditSymptoms: () => void;
  onViewCarePathway?: (diagnosisId: string, diagnosisName: string, mode: 'view' | 'create') => void;
  showCarePathwayButtons?: boolean;
}

export function ResultsMessage({
  symptoms,
  files,
  diagnoses,
  onToggleDiagnosis,
  onEditSymptoms,
  onViewCarePathway,
  showCarePathwayButtons = true
}: ResultsMessageProps) {

  return (
    <div className="px-4 py-4 space-y-4">
      {/* Symptoms Summary */}
      <div className="bg-white/60 backdrop-blur-sm rounded-lg p-4">
        <div className="flex items-start gap-3 mb-3">
          <button
            onClick={onEditSymptoms}
            className="flex-shrink-0 w-8 h-8 flex items-center justify-center rounded-lg bg-[#4b4ad5]/10 hover:bg-[#4b4ad5]/20 transition-colors"
            aria-label="Edit symptoms"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#4b4ad5" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
            </svg>
          </button>
          <p className="flex-1 text-sm text-[#171725] leading-relaxed">
            {symptoms}
          </p>
        </div>

        {/* Files */}
        {files.length > 0 && (
          <div className="flex gap-2 flex-wrap">
            {files.map((file, index) => (
              <div key={index} className="flex items-center gap-1 px-3 py-1.5 bg-red-50 rounded-lg border border-red-200">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="#dc2626">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8" fill="white"/>
                </svg>
                <span className="text-xs text-red-700 truncate max-w-[120px]">
                  {file.name}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Results Header */}
      <div className="flex gap-3 items-start">
        <div className="flex-shrink-0 w-8 h-8 bg-[#4b4ad5] rounded-lg flex items-center justify-center p-1">
          <Image
            src="/assets/7ad7187d00371975974120ce650f92bc58dd31fb.svg"
            alt="AI"
            width={24}
            height={24}
            className="w-full h-full"
          />
        </div>
        <div className="flex-1">
          <p className="text-[#171725] text-sm leading-relaxed">
            Your DDx has been generated. Please find the results below.
          </p>
        </div>
        <button
          className="flex-shrink-0 w-10 h-10 flex items-center justify-center rounded-lg hover:bg-white/50 transition-colors"
          aria-label="Share results"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#4b4ad5" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/>
            <polyline points="16 6 12 2 8 6"/>
            <line x1="12" x2="12" y1="2" y2="15"/>
          </svg>
        </button>
      </div>

      {/* Most Likely Section */}
      <div>
        <div className="shadow-sm">
          {diagnoses.map((diagnosis, index) => (
            <DiagnosisCard
              key={diagnosis.id}
              diagnosis={diagnosis}
              onToggle={() => onToggleDiagnosis(diagnosis.id)}
              onViewCarePathway={onViewCarePathway}
              showCarePathwayButton={showCarePathwayButtons}
              isFirst={index === 0}
              isLast={index === diagnoses.length - 1}
            />
          ))}
        </div>
      </div>

      {/* Disclaimer */}
      <div className="pt-4 border-t border-gray-200">
        <p className="text-xs text-[#6b7280] leading-relaxed">
          <strong>Disclaimer:</strong> These results are generated by AI and should be used as a guide, not the final source for patient treatment decisions.
        </p>
      </div>
    </div>
  );
}
